### ISSUE TITLE
Generated UUIDs are uppercase

### ISSUE THREAD

**Issue by s5no5t** [TerraVenil/guid#3]
I really like this useful extension!

However, [according to the spec](http://www.itu.int/rec/T-REC-X.667/en), all generated UUIDs should be lowercase (see [SO description](http://stackoverflow.com/a/13833488) for details.

However, the UUIDs generated here aren't - they are explicitly uppercase.

Is there a reason for this behavior?

**Comment by TerraVenil** [comment]
Hi! Nice to read thay it's useful! Yes, there was only one reason to use uppercase for UUIDs. I used guid extension on project which historically in SQL scripts have used uppercase.

**Comment by s5no5t** [comment]
Ok, well are you interested in a bug fix?

Am 19.04.2017 5:55 nachm. schrieb "Alexey Borodenko" <
notifications@github.com>:

**Comment by Dagur** [comment]
A setting to make lowercase UUID's would be nice

**Comment by TerraVenil** [comment]
I would appreciate it if you create PR with available options on how to use this extension within UUIDs in upper case or lower case.
@jugglingthebits

**Comment by Hobart2967** [comment]
There you go https://github.com/TerraVenil/guid/pull/4

**Comment by TerraVenil** [comment]
@Hobart2967 great contribution! 👍

**Comment by Hobart2967** [comment]
Thank you! When's this going to be released to the market place?  https://marketplace.visualstudio.com/items?itemName=kosunix.guid

**Comment by TerraVenil** [comment]
Waiting for any volunteer to pick up the https://github.com/TerraVenil/guid/issues/5.

**Comment by Hobart2967** [comment]
Done: https://github.com/TerraVenil/guid/pull/6
