### ISSUE TITLE
Migrate from https://github.com/broofa/node-uuid

### ISSUE THREAD

**Issue by TerraVenil** [TerraVenil/guid#5]
Found that https://github.com/broofa/node-uuid no longer supported. So it would be nice to migrate it to https://github.com/uuidjs/uuid.

**Comment by Hobart2967** [comment]
There you go ;)

**Comment by TerraVenil** [comment]
@Hobart2967 do you want to try another one https://github.com/TerraVenil/guid/issues/7 ?🤓

**Comment by Hobart2967** [comment]
Will have a Look this afternoon :)
