### ISSUE TITLE
Integrate GitHub Actions for publishing VS Code extension

### ISSUE THREAD

**Issue by TerraVenil** [TerraVenil/guid#7]
To be able to automate the process of publishing VS Code extension to https://marketplace.visualstudio.com/ integration with GitHub Actions needed, and specifically with https://github.com/marketplace/actions/publish-vs-code-extension.

**Comment by Hobart2967** [comment]
There you go ;) https://github.com/TerraVenil/guid/pull/8  @TerraVenil

**Comment by Hobart2967** [comment]
PS: Next time, you owe me a beer 😛
